### ISSUE TITLE
Chat GPT missing context of conversation

### ISSUE THREAD

**Issue by lukcz** [Hassassistant/openai_response#1]
I've just checked on addon and it's great. except that Chat GPT does not store conversation history.
When You ask him about 1 thing , and in the second question You ask to give more details, he seems to get lost.

**Comment by Hassassistant** [comment]
that is correct, I initially started with the intent of chat history. with the current ChatGPT price model, this would get pretty expensive as you would need to include your chat history with every prompt.

be assured, this is early days, I will be re-visiting this after I take some time to reflect (looking into bing chat api currently for the conversation aspect) and I will be investigating how to improve this model further.
