### ISSUE TITLE
Add the ability to include a prompt.

### ISSUE THREAD

**Issue by davidlamkin** [Hassassistant/openai_response#2]
Great work! Unlike using a "conversation" in HA, this could actually DO something! It would be great if you can include a prompt in the conversation prior to submitting from the input text. A key component would be the ability to template the prompt with HA data.

**Comment by Hassassistant** [comment]
Yeah so a system prompt would be ideal. I have this down for an update when I eventually get around to pushing changes. Thanks for the support 👍🏻
