### ISSUE TITLE
input_text limitation

### ISSUE THREAD

**Issue by Olen** [Hassassistant/openai_response#3]
Hi, and thanks for a great integration.  Just what I was looking for.
I am currently using it to make voice announcements more dynamic and fun.  However, I am often hitting the limit if 255 characters in the input_text to create the request.
For instance I want it to generate a weather report based on a lot of sensor data, but that request very easily exceeds 255 characters.
As far as I know, there is no such limit in a servce call, as as service_data element can be of any size and type.

So would it be an option to extend this integration with a service call that can be used instead of/in addition to the input_text?

**Comment by Molodax** [comment]
I'm trying to use it for a similar purpose like make a short summary from a number of values (e.g. weather forecast) but limitation of input_text to 255 symbols make it very difficult.

**Comment by Olen** [comment]
Take a look at #6 
It adds a service call in addition to the input_text, so you can use longer prompts.
It also upgrades to gpt-3.5
